# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class Deployment(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, uuid=None, testartifact_uuid=None):  # noqa: E501
        """Deployment - a model defined in OpenAPI

        :param uuid: The uuid of this Deployment.  # noqa: E501
        :type uuid: str
        :param testartifact_uuid: The testartifact_uuid of this Deployment.  # noqa: E501
        :type testartifact_uuid: str
        """
        self.openapi_types = {
            'uuid': str,
            'testartifact_uuid': str
        }

        self.attribute_map = {
            'uuid': 'uuid',
            'testartifact_uuid': 'testartifact_uuid'
        }

        self._uuid = uuid
        self._testartifact_uuid = testartifact_uuid

    @classmethod
    def from_dict(cls, dikt) -> 'Deployment':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Deployment of this Deployment.  # noqa: E501
        :rtype: Deployment
        """
        return util.deserialize_model(dikt, cls)

    @property
    def uuid(self):
        """Gets the uuid of this Deployment.


        :return: The uuid of this Deployment.
        :rtype: str
        """
        return self._uuid

    @uuid.setter
    def uuid(self, uuid):
        """Sets the uuid of this Deployment.


        :param uuid: The uuid of this Deployment.
        :type uuid: str
        """

        self._uuid = uuid

    @property
    def testartifact_uuid(self):
        """Gets the testartifact_uuid of this Deployment.


        :return: The testartifact_uuid of this Deployment.
        :rtype: str
        """
        return self._testartifact_uuid

    @testartifact_uuid.setter
    def testartifact_uuid(self, testartifact_uuid):
        """Sets the testartifact_uuid of this Deployment.


        :param testartifact_uuid: The testartifact_uuid of this Deployment.
        :type testartifact_uuid: str
        """

        self._testartifact_uuid = testartifact_uuid
