# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class Execution(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, uuid=None, deployment_uuid=None):  # noqa: E501
        """Execution - a model defined in OpenAPI

        :param uuid: The uuid of this Execution.  # noqa: E501
        :type uuid: str
        :param deployment_uuid: The deployment_uuid of this Execution.  # noqa: E501
        :type deployment_uuid: str
        """
        self.openapi_types = {
            'uuid': str,
            'deployment_uuid': str
        }

        self.attribute_map = {
            'uuid': 'uuid',
            'deployment_uuid': 'deployment_uuid'
        }

        self._uuid = uuid
        self._deployment_uuid = deployment_uuid

    @classmethod
    def from_dict(cls, dikt) -> 'Execution':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Execution of this Execution.  # noqa: E501
        :rtype: Execution
        """
        return util.deserialize_model(dikt, cls)

    @property
    def uuid(self):
        """Gets the uuid of this Execution.


        :return: The uuid of this Execution.
        :rtype: str
        """
        return self._uuid

    @uuid.setter
    def uuid(self, uuid):
        """Sets the uuid of this Execution.


        :param uuid: The uuid of this Execution.
        :type uuid: str
        """

        self._uuid = uuid

    @property
    def deployment_uuid(self):
        """Gets the deployment_uuid of this Execution.


        :return: The deployment_uuid of this Execution.
        :rtype: str
        """
        return self._deployment_uuid

    @deployment_uuid.setter
    def deployment_uuid(self, deployment_uuid):
        """Sets the deployment_uuid of this Execution.


        :param deployment_uuid: The deployment_uuid of this Execution.
        :type deployment_uuid: str
        """

        self._deployment_uuid = deployment_uuid
