# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.node_test import NodeTest
from openapi_server import util

from openapi_server.models.node_test import NodeTest  # noqa: E501

class PolicyTest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, node_tests=None, policy=None, project_id=None, status=None, testartifact_id=None):  # noqa: E501
        """PolicyTest - a model defined in OpenAPI

        :param id: The id of this PolicyTest.  # noqa: E501
        :type id: int
        :param node_tests: The node_tests of this PolicyTest.  # noqa: E501
        :type node_tests: List[NodeTest]
        :param policy: The policy of this PolicyTest.  # noqa: E501
        :type policy: str
        :param project_id: The project_id of this PolicyTest.  # noqa: E501
        :type project_id: int
        :param status: The status of this PolicyTest.  # noqa: E501
        :type status: str
        :param testartifact_id: The testartifact_id of this PolicyTest.  # noqa: E501
        :type testartifact_id: int
        """
        self.openapi_types = {
            'id': int,
            'node_tests': List[NodeTest],
            'policy': str,
            'project_id': int,
            'status': str,
            'testartifact_id': int
        }

        self.attribute_map = {
            'id': 'id',
            'node_tests': 'nodeTests',
            'policy': 'policy',
            'project_id': 'projectId',
            'status': 'status',
            'testartifact_id': 'testartifactId'
        }

        self._id = id
        self._node_tests = node_tests
        self._policy = policy
        self._project_id = project_id
        self._status = status
        self._testartifact_id = testartifact_id

    @classmethod
    def from_dict(cls, dikt) -> 'PolicyTest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PolicyTest of this PolicyTest.  # noqa: E501
        :rtype: PolicyTest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this PolicyTest.


        :return: The id of this PolicyTest.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this PolicyTest.


        :param id: The id of this PolicyTest.
        :type id: int
        """

        self._id = id

    @property
    def node_tests(self):
        """Gets the node_tests of this PolicyTest.


        :return: The node_tests of this PolicyTest.
        :rtype: List[NodeTest]
        """
        return self._node_tests

    @node_tests.setter
    def node_tests(self, node_tests):
        """Sets the node_tests of this PolicyTest.


        :param node_tests: The node_tests of this PolicyTest.
        :type node_tests: List[NodeTest]
        """

        self._node_tests = node_tests

    @property
    def policy(self):
        """Gets the policy of this PolicyTest.


        :return: The policy of this PolicyTest.
        :rtype: str
        """
        return self._policy

    @policy.setter
    def policy(self, policy):
        """Sets the policy of this PolicyTest.


        :param policy: The policy of this PolicyTest.
        :type policy: str
        """

        self._policy = policy

    @property
    def project_id(self):
        """Gets the project_id of this PolicyTest.


        :return: The project_id of this PolicyTest.
        :rtype: int
        """
        return self._project_id

    @project_id.setter
    def project_id(self, project_id):
        """Sets the project_id of this PolicyTest.


        :param project_id: The project_id of this PolicyTest.
        :type project_id: int
        """

        self._project_id = project_id

    @property
    def status(self):
        """Gets the status of this PolicyTest.


        :return: The status of this PolicyTest.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this PolicyTest.


        :param status: The status of this PolicyTest.
        :type status: str
        """

        self._status = status

    @property
    def testartifact_id(self):
        """Gets the testartifact_id of this PolicyTest.


        :return: The testartifact_id of this PolicyTest.
        :rtype: int
        """
        return self._testartifact_id

    @testartifact_id.setter
    def testartifact_id(self, testartifact_id):
        """Sets the testartifact_id of this PolicyTest.


        :param testartifact_id: The testartifact_id of this PolicyTest.
        :type testartifact_id: int
        """

        self._testartifact_id = testartifact_id
