# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class POSTDeployment(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, testartifact_uuid=None):  # noqa: E501
        """POSTDeployment - a model defined in OpenAPI

        :param testartifact_uuid: The testartifact_uuid of this POSTDeployment.  # noqa: E501
        :type testartifact_uuid: str
        """
        self.openapi_types = {
            'testartifact_uuid': str
        }

        self.attribute_map = {
            'testartifact_uuid': 'testartifact_uuid'
        }

        self._testartifact_uuid = testartifact_uuid

    @classmethod
    def from_dict(cls, dikt) -> 'POSTDeployment':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The POSTDeployment of this POSTDeployment.  # noqa: E501
        :rtype: POSTDeployment
        """
        return util.deserialize_model(dikt, cls)

    @property
    def testartifact_uuid(self):
        """Gets the testartifact_uuid of this POSTDeployment.


        :return: The testartifact_uuid of this POSTDeployment.
        :rtype: str
        """
        return self._testartifact_uuid

    @testartifact_uuid.setter
    def testartifact_uuid(self, testartifact_uuid):
        """Sets the testartifact_uuid of this POSTDeployment.


        :param testartifact_uuid: The testartifact_uuid of this POSTDeployment.
        :type testartifact_uuid: str
        """
        if testartifact_uuid is None:
            raise ValueError("Invalid value for `testartifact_uuid`, must not be `None`")  # noqa: E501

        self._testartifact_uuid = testartifact_uuid
