# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class POSTExecution(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, deployment_uuid=None):  # noqa: E501
        """POSTExecution - a model defined in OpenAPI

        :param deployment_uuid: The deployment_uuid of this POSTExecution.  # noqa: E501
        :type deployment_uuid: str
        """
        self.openapi_types = {
            'deployment_uuid': str
        }

        self.attribute_map = {
            'deployment_uuid': 'deployment_uuid'
        }

        self._deployment_uuid = deployment_uuid

    @classmethod
    def from_dict(cls, dikt) -> 'POSTExecution':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The POSTExecution of this POSTExecution.  # noqa: E501
        :rtype: POSTExecution
        """
        return util.deserialize_model(dikt, cls)

    @property
    def deployment_uuid(self):
        """Gets the deployment_uuid of this POSTExecution.


        :return: The deployment_uuid of this POSTExecution.
        :rtype: str
        """
        return self._deployment_uuid

    @deployment_uuid.setter
    def deployment_uuid(self, deployment_uuid):
        """Sets the deployment_uuid of this POSTExecution.


        :param deployment_uuid: The deployment_uuid of this POSTExecution.
        :type deployment_uuid: str
        """
        if deployment_uuid is None:
            raise ValueError("Invalid value for `deployment_uuid`, must not be `None`")  # noqa: E501

        self._deployment_uuid = deployment_uuid
