# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class POSTProject(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, repository_url=None):  # noqa: E501
        """POSTProject - a model defined in OpenAPI

        :param name: The name of this POSTProject.  # noqa: E501
        :type name: str
        :param repository_url: The repository_url of this POSTProject.  # noqa: E501
        :type repository_url: str
        """
        self.openapi_types = {
            'name': str,
            'repository_url': str
        }

        self.attribute_map = {
            'name': 'name',
            'repository_url': 'repository_url'
        }

        self._name = name
        self._repository_url = repository_url

    @classmethod
    def from_dict(cls, dikt) -> 'POSTProject':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The POSTProject of this POSTProject.  # noqa: E501
        :rtype: POSTProject
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self):
        """Gets the name of this POSTProject.


        :return: The name of this POSTProject.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this POSTProject.


        :param name: The name of this POSTProject.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def repository_url(self):
        """Gets the repository_url of this POSTProject.


        :return: The repository_url of this POSTProject.
        :rtype: str
        """
        return self._repository_url

    @repository_url.setter
    def repository_url(self, repository_url):
        """Sets the repository_url of this POSTProject.


        :param repository_url: The repository_url of this POSTProject.
        :type repository_url: str
        """
        if repository_url is None:
            raise ValueError("Invalid value for `repository_url`, must not be `None`")  # noqa: E501

        self._repository_url = repository_url
