# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class POSTWorkflow(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, _workflow_data=None):  # noqa: E501
        self.openapi_types = {
            '_workflow_data': str
        }

        self.attribute_map = {
            '_workflow_data': '_workflow_data'
        }

        self._workflow_data = _workflow_data

    @classmethod
    def from_dict(cls, dikt) -> 'POSTWorkflow':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The POSTExecution of this POSTExecution.  # noqa: E501
        :rtype: POSTExecution
        """
        return util.deserialize_model(dikt, cls)

    @property
    def workflow_data(self):
        return self._workflow_data

    @workflow_data.setter
    def workflow_data(self, workflow_data):
        if workflow_data is None:
            raise ValueError("Invalid value for `deployment_uuid`, must not be `None`")  # noqa: E501

        self._workflow_data = workflow_data
