# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class POSTExecutors(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, deployment_id=None):  # noqa: E501
        """POSTExecutors - a model defined in OpenAPI

        :param deployment_id: The deployment_id of this POSTExecutors.  # noqa: E501
        :type deployment_id: int
        """
        self.openapi_types = {
            'deployment_id': int
        }

        self.attribute_map = {
            'deployment_id': 'deploymentId'
        }

        self._deployment_id = deployment_id

    @classmethod
    def from_dict(cls, dikt) -> 'POSTExecutors':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The POSTExecutors of this POSTExecutors.  # noqa: E501
        :rtype: POSTExecutors
        """
        return util.deserialize_model(dikt, cls)

    @property
    def deployment_id(self):
        """Gets the deployment_id of this POSTExecutors.


        :return: The deployment_id of this POSTExecutors.
        :rtype: int
        """
        return self._deployment_id

    @deployment_id.setter
    def deployment_id(self, deployment_id):
        """Sets the deployment_id of this POSTExecutors.


        :param deployment_id: The deployment_id of this POSTExecutors.
        :type deployment_id: int
        """
        if deployment_id is None:
            raise ValueError("Invalid value for `deployment_id`, must not be `None`")  # noqa: E501

        self._deployment_id = deployment_id
