# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class TestArtifact(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, uuid=None, project_uuid=None, sut_tosca_path=None, ti_tosca_path=None, commit_hash=None):  # noqa: E501
        """TestArtifact - a model defined in OpenAPI

        :param uuid: The uuid of this TestArtifact.  # noqa: E501
        :type uuid: str
        :param project_uuid: The project_uuid of this TestArtifact.  # noqa: E501
        :type project_uuid: str
        :param sut_tosca_path: The sut_tosca_path of this TestArtifact.  # noqa: E501
        :type sut_tosca_path: str
        :param ti_tosca_path: The ti_tosca_path of this TestArtifact.  # noqa: E501
        :type ti_tosca_path: str
        :param commit_hash: The commit_hash of this TestArtifact.  # noqa: E501
        :type commit_hash: str
        """
        self.openapi_types = {
            'uuid': str,
            'project_uuid': str,
            'sut_tosca_path': str,
            'ti_tosca_path': str,
            'commit_hash': str
        }

        self.attribute_map = {
            'uuid': 'uuid',
            'project_uuid': 'project_uuid',
            'sut_tosca_path': 'sut_tosca_path',
            'ti_tosca_path': 'ti_tosca_path',
            'commit_hash': 'commit_hash'
        }

        self._uuid = uuid
        self._project_uuid = project_uuid
        self._sut_tosca_path = sut_tosca_path
        self._ti_tosca_path = ti_tosca_path
        self._commit_hash = commit_hash

    @classmethod
    def from_dict(cls, dikt) -> 'TestArtifact':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TestArtifact of this TestArtifact.  # noqa: E501
        :rtype: TestArtifact
        """
        return util.deserialize_model(dikt, cls)

    @property
    def uuid(self):
        """Gets the uuid of this TestArtifact.


        :return: The uuid of this TestArtifact.
        :rtype: str
        """
        return self._uuid

    @uuid.setter
    def uuid(self, uuid):
        """Sets the uuid of this TestArtifact.


        :param uuid: The uuid of this TestArtifact.
        :type uuid: str
        """

        self._uuid = uuid

    @property
    def project_uuid(self):
        """Gets the project_uuid of this TestArtifact.


        :return: The project_uuid of this TestArtifact.
        :rtype: str
        """
        return self._project_uuid

    @project_uuid.setter
    def project_uuid(self, project_uuid):
        """Sets the project_uuid of this TestArtifact.


        :param project_uuid: The project_uuid of this TestArtifact.
        :type project_uuid: str
        """

        self._project_uuid = project_uuid

    @property
    def sut_tosca_path(self):
        """Gets the sut_tosca_path of this TestArtifact.


        :return: The sut_tosca_path of this TestArtifact.
        :rtype: str
        """
        return self._sut_tosca_path

    @sut_tosca_path.setter
    def sut_tosca_path(self, sut_tosca_path):
        """Sets the sut_tosca_path of this TestArtifact.


        :param sut_tosca_path: The sut_tosca_path of this TestArtifact.
        :type sut_tosca_path: str
        """

        self._sut_tosca_path = sut_tosca_path

    @property
    def ti_tosca_path(self):
        """Gets the ti_tosca_path of this TestArtifact.


        :return: The ti_tosca_path of this TestArtifact.
        :rtype: str
        """
        return self._ti_tosca_path

    @ti_tosca_path.setter
    def ti_tosca_path(self, ti_tosca_path):
        """Sets the ti_tosca_path of this TestArtifact.


        :param ti_tosca_path: The ti_tosca_path of this TestArtifact.
        :type ti_tosca_path: str
        """

        self._ti_tosca_path = ti_tosca_path

    @property
    def commit_hash(self):
        """Gets the commit_hash of this TestArtifact.


        :return: The commit_hash of this TestArtifact.
        :rtype: str
        """
        return self._commit_hash

    @commit_hash.setter
    def commit_hash(self, commit_hash):
        """Sets the commit_hash of this TestArtifact.


        :param commit_hash: The commit_hash of this TestArtifact.
        :type commit_hash: str
        """

        self._commit_hash = commit_hash
