# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class Executor(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, deployment_id=None, id=None, project_id=None, status=None):  # noqa: E501
        """Executor - a model defined in OpenAPI

        :param deployment_id: The deployment_id of this Executor.  # noqa: E501
        :type deployment_id: int
        :param id: The id of this Executor.  # noqa: E501
        :type id: int
        :param project_id: The project_id of this Executor.  # noqa: E501
        :type project_id: int
        :param status: The status of this Executor.  # noqa: E501
        :type status: str
        """
        self.openapi_types = {
            'deployment_id': int,
            'id': int,
            'project_id': int,
            'status': str
        }

        self.attribute_map = {
            'deployment_id': 'deploymentId',
            'id': 'id',
            'project_id': 'projectId',
            'status': 'status'
        }

        self._deployment_id = deployment_id
        self._id = id
        self._project_id = project_id
        self._status = status

    @classmethod
    def from_dict(cls, dikt) -> 'Executor':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Executor of this Executor.  # noqa: E501
        :rtype: Executor
        """
        return util.deserialize_model(dikt, cls)

    @property
    def deployment_id(self):
        """Gets the deployment_id of this Executor.


        :return: The deployment_id of this Executor.
        :rtype: int
        """
        return self._deployment_id

    @deployment_id.setter
    def deployment_id(self, deployment_id):
        """Sets the deployment_id of this Executor.


        :param deployment_id: The deployment_id of this Executor.
        :type deployment_id: int
        """

        self._deployment_id = deployment_id

    @property
    def id(self):
        """Gets the id of this Executor.


        :return: The id of this Executor.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Executor.


        :param id: The id of this Executor.
        :type id: int
        """

        self._id = id

    @property
    def project_id(self):
        """Gets the project_id of this Executor.


        :return: The project_id of this Executor.
        :rtype: int
        """
        return self._project_id

    @project_id.setter
    def project_id(self, project_id):
        """Sets the project_id of this Executor.


        :param project_id: The project_id of this Executor.
        :type project_id: int
        """

        self._project_id = project_id

    @property
    def status(self):
        """Gets the status of this Executor.


        :return: The status of this Executor.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this Executor.


        :param status: The status of this Executor.
        :type status: str
        """

        self._status = status
