# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build and push Docker image to DockerHub

on:
  push:
    branches:
    - master
    - dev
jobs:
  push_to_registry:
    name: Build and push Docker image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Branch name
        run: echo "GITHUB_BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.docker_hub_user }}
          password: ${{ secrets.docker_hub_pass }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: radonconsortium/radon-ctt:${GITHUB_BRANCH}
          context: ./ctt-server
