name: Build and push Docker image to DockerHub

on:
  push:
    branches:
    - master
    - dev
jobs:
  build_docker_image:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Branch name
        run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: radonconsortium/radon-ctt:${{ env.BRANCH }}
          context: ./ctt-server
  push_docker_image:
    needs: build_docker_image
    name: Push Docker image to DockerHub
    runs-on: ubuntu-latest
    steps:
    - name: Branch name
      run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.docker_hub_user }}
        password: ${{ secrets.docker_hub_pass }}
    - name: Push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: radonconsortium/radon-ctt:${{ env.BRANCH }}
        context: ./ctt-server
