name: Build and push Docker image to DockerHub

on:
  push:
    branches:
    - master
    - dev
jobs:
  docker_image:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Branch name
        run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Branch name
        run: echo "RUNNER_TMP=${RUNNER_TEMP}" >> $GITHUB_ENV        
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.docker_hub_user }}
          password: ${{ secrets.docker_hub_pass }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: radonconsortium/radon-ctt:${{ env.BRANCH }}
          context: ./ctt-server
      - name: Run tests with coverage
        run: docker run -e 'CTT_TEST_MODE=True' -v '/home/runner/work/_temp/_github_home:/output' --entrypoint '/bin/sh' radonconsortium/radon-ctt:${{ env.BRANCH }} -c 'coverage run -m xmlrunner discover openapi_server/test/ -o /output/unittest && coverage xml -o /output/coverage.xml'"
      - name: Upload test artifacts
        uses: actions/upload-artifact@v2
        with:
          name: test-artifacts
          path: |
            /home/runner/work/_temp/_github_home/coverage.xml
            /home/runner/work/_temp/_github_home/unittest
